import { Button, Card, Field, Money, Page, StatusPill, type } from '@/components/ui-kit';
import { colors, radii, spacing } from '@/constants/yeskaro-theme';
import { useApp } from '@/context/app-context';
import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

type Tab = 'funding' | 'payouts' | 'disputes' | 'overview';
export default function Admin() {
  const { user, funding, payouts, disputes, projects, actOnQueue, resolveDispute } = useApp();
  const [tab, setTab] = useState<Tab>('funding'); const [buyerSplit, setBuyerSplit] = useState('25'); const [note, setNote] = useState('');
  if (!user) { router.replace('/'); return null; }
  return <Page><View><Text style={type.eyebrow}>Admin operations</Text><Text style={type.h1}>Review queues</Text><Text style={type.body}>All payment movement below is simulated and requires a manual bank transfer.</Text></View><View style={styles.tabs}>{(['funding', 'payouts', 'disputes', 'overview'] as Tab[]).map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.tabActive]}><Text style={tab === item ? styles.tabTextActive : styles.tabText}>{item}</Text></Pressable>)}</View>
    {tab === 'funding' && <View style={styles.list}>{funding.map((item) => <Card key={item.id}><View style={styles.queueHeader}><View><Text style={type.h3}>{item.title}</Text><Text style={type.small}>{item.person} • {item.meta}</Text></View><Money amount={item.amount} large /></View><View style={styles.receipt}><Text style={styles.receiptIcon}>▧</Text><Text style={type.small}>Bank-transfer receipt preview</Text></View><View style={styles.actions}><StatusPill value={item.status} />{item.status === 'pending' && <><Button label="Reject" variant="danger" compact onPress={() => actOnQueue('funding', item.id, 'reject')} /><Button label="Approve funding" compact onPress={() => actOnQueue('funding', item.id, 'approve')} /></>}</View></Card>)}</View>}
    {tab === 'payouts' && <View style={styles.list}><Card style={styles.warning}><Text style={type.h3}>Simulated payouts</Text><Text style={type.body}>Transfer funds manually using the verified bank details, then mark the payout as sent.</Text></Card>{payouts.map((item) => <Card key={item.id}><View style={styles.queueHeader}><View><Text style={type.h3}>{item.title}</Text><Text style={type.small}>{item.person} • {item.meta}</Text></View><Money amount={item.amount} large /></View><View style={styles.actions}><StatusPill value={item.status} />{item.status === 'pending_admin_payout' && <Button label="Mark simulated payout as sent" onPress={() => actOnQueue('payout', item.id, 'approve')} />}</View></Card>)}</View>}
    {tab === 'disputes' && disputes.map((item) => <Card key={item.id}><View style={styles.queueHeader}><View><StatusPill value={item.status} /><Text style={type.h2}>{item.title}</Text></View><Text style={styles.confidence}>{Math.round(item.confidence * 100)}% AI confidence</Text></View><View style={styles.columns}><View style={styles.column}><Text style={type.eyebrow}>Buyer claim</Text><Text style={type.body}>{item.buyerStatement}</Text></View><View style={styles.column}><Text style={type.eyebrow}>Seller response</Text><Text style={type.body}>{item.sellerStatement}</Text></View></View><View style={styles.ai}><Text style={type.eyebrow}>Private AI recommendation</Text><Text style={type.h3}>Seller {item.sellerSharePercent}% / Buyer {item.buyerSharePercent}%</Text><Text style={type.body}>{item.reasoning}</Text></View>{item.status !== 'resolved' && <View style={styles.resolve}><Field label="Buyer share %" value={buyerSplit} keyboardType="numeric" onChangeText={setBuyerSplit} /><Field label="Admin ruling note" value={note} onChangeText={setNote} multiline placeholder="Explain the final decision to both parties…" /><Button label="Confirm final ruling" onPress={() => resolveDispute(item.id, Math.max(0, Math.min(100, Number(buyerSplit))), note)} /></View>}</Card>)}
    {tab === 'overview' && <Card><Text style={type.h2}>Users & projects</Text><View style={styles.tableHead}><Text style={styles.cell}>Project</Text><Text style={styles.cell}>Status</Text><Text style={styles.cell}>Escrow</Text></View>{projects.map((project) => <View key={project.id} style={styles.tableRow}><Text style={styles.cellStrong}>{project.title}</Text><View style={styles.cell}><StatusPill value={project.status} /></View><View style={styles.cell}><Money amount={project.totalAmount} /></View></View>)}</Card>}
  </Page>;
}
const styles = StyleSheet.create({
  tabs: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, tab: { paddingVertical: 10, paddingHorizontal: 16, borderRadius: radii.pill, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }, tabActive: { backgroundColor: colors.brand, borderColor: colors.brand }, tabText: { color: colors.muted, fontWeight: '700', textTransform: 'capitalize' }, tabTextActive: { color: colors.white, fontWeight: '800', textTransform: 'capitalize' }, list: { gap: spacing.lg }, queueHeader: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', alignItems: 'center', gap: spacing.md }, receipt: { height: 150, borderRadius: radii.md, backgroundColor: colors.canvas, alignItems: 'center', justifyContent: 'center', gap: spacing.sm }, receiptIcon: { color: colors.brand, fontSize: 34 }, actions: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', alignItems: 'center', gap: spacing.sm }, warning: { backgroundColor: colors.warningSoft }, confidence: { color: colors.brand, fontWeight: '800' }, columns: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.lg }, column: { flex: 1, minWidth: 260 }, ai: { backgroundColor: colors.brandSoft, borderRadius: radii.md, padding: spacing.lg, gap: spacing.sm }, resolve: { gap: spacing.md, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: spacing.lg }, tableHead: { flexDirection: 'row', paddingBottom: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border }, tableRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border }, cell: { flex: 1, color: colors.muted, fontSize: 13 }, cellStrong: { flex: 1, color: colors.ink, fontWeight: '700' },
});
