import { AppHeader } from '@/components/app-chrome';
import { Money, Page, ProgressBar } from '@/components/ui-kit';
import { colors, fonts, radii, spacing } from '@/constants/yeskaro-theme';
import { useApp } from '@/context/app-context';
import { router } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';

type Filter = 'All' | 'Incoming' | 'Outgoing';
export default function Escrows() {
  const { projects, user } = useApp(); const { width } = useWindowDimensions(); const [filter, setFilter] = useState<Filter>('All'); const [search, setSearch] = useState('');
  const visible = useMemo(() => projects.filter((project) => project.title.toLowerCase().includes(search.toLowerCase())), [projects, search]);
  if (!user) return null;
  return <Page><AppHeader title="Escrows" subtitle="Protected transactions" /><View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><TextInput value={search} onChangeText={setSearch} placeholder="Search name, username or escrow ID" placeholderTextColor={colors.tertiary} style={styles.searchInput} /></View>
    <View style={styles.filters}>{(['All', 'Incoming', 'Outgoing'] as Filter[]).map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.filterActive]}><Text style={[styles.filterText, filter === item && styles.filterTextActive]}>{item}</Text></Pressable>)}</View>
    <View style={styles.subfilters}>{['Awaiting Me', 'Active', 'Completed'].map((item) => <View key={item} style={styles.subfilter}><Text style={styles.subfilterText}>{item}</Text></View>)}</View>
    <View style={[styles.grid, width >= 800 && styles.gridWide]}>{visible.map((project) => { const completed = project.milestones.filter((m) => ['paid', 'approved'].includes(m.status)).length; const action = project.milestones.find((m) => m.status === 'submitted'); return <Pressable key={project.id} onPress={() => router.push(`/project/${project.id}`)} style={[styles.card, width >= 800 && styles.cardWide, action && styles.cardAttention]}><View style={styles.cardHead}><View style={{ flex: 1 }}><Text style={styles.cardTitle}>{project.title}</Text><Text style={styles.party}>{user.role === 'buyer' ? 'Faraz' : 'Ajmal'}</Text></View><Money amount={project.totalAmount} /></View><Text style={styles.meta}>Freelance • {user.role === 'buyer' ? 'Outgoing' : 'Incoming'}</Text><Text style={[styles.status, action && styles.statusAttention]}>{action ? `${action.title} ready for review` : `${completed} of ${project.milestones.length} milestones complete`}</Text><ProgressBar value={project.milestones.length ? completed / project.milestones.length * 100 : 0} /></Pressable>; })}</View>
  </Page>;
}
const styles = StyleSheet.create({
  search: { height: 45, borderRadius: 12, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13 }, searchIcon: { color: colors.tertiary, fontFamily: fonts.regular, fontSize: 17 }, searchInput: { flex: 1, height: 44, color: colors.ink, fontFamily: fonts.regular, fontSize: 11 }, filters: { flexDirection: 'row', alignSelf: 'flex-start', backgroundColor: colors.surface }, filter: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: radii.pill }, filterActive: { backgroundColor: colors.brand }, filterText: { color: colors.muted, fontFamily: fonts.medium, fontSize: 10.5 }, filterTextActive: { color: colors.white }, subfilters: { flexDirection: 'row', gap: 6 }, subfilter: { backgroundColor: colors.surfaceSubtle, paddingHorizontal: 10, paddingVertical: 6, borderRadius: radii.pill }, subfilterText: { color: colors.muted, fontFamily: fonts.medium, fontSize: 9 }, grid: { gap: spacing.lg }, gridWide: { flexDirection: 'row', flexWrap: 'wrap' }, card: { width: '100%', minHeight: 148, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 16, padding: 15, gap: 8 }, cardWide: { flexGrow: 1, flexBasis: 320, maxWidth: 520 }, cardAttention: { backgroundColor: colors.warningSoft, borderColor: colors.warning }, cardHead: { flexDirection: 'row', alignItems: 'flex-start' }, cardTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 14.5 }, party: { color: colors.muted, fontFamily: fonts.regular, fontSize: 10.5 }, meta: { color: colors.brand, fontFamily: fonts.medium, fontSize: 10.5 }, status: { color: colors.muted, fontFamily: fonts.medium, fontSize: 11.5 }, statusAttention: { color: colors.warning },
});
