import { BackButton, Button, Page, type } from '@/components/ui-kit';
import { colors, fonts, radii, spacing } from '@/constants/yeskaro-theme';
import { useApp } from '@/context/app-context';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';

const rows = [
  ['Personal information', 'Mobile, email and address'], ['Identity & verification', 'Verified identity details'], ['Linked accounts', 'Bank and mobile-wallet accounts'], ['Security', 'Password, PIN, biometrics and devices'], ['Notifications', 'Transaction and security preferences'],
];
export default function Profile() {
  const { user, logout } = useApp(); if (!user) return null; const initials = user.name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();
  return <Page><BackButton /><Text style={type.h1}>Profile</Text><View style={styles.avatar}><Text style={styles.avatarText}>{initials}</Text></View><Text style={type.h3}>{user.name}</Text><Text style={styles.verified}>@{user.email.split('@')[0]} • Verified</Text><View style={styles.rows}>{rows.map(([title, subtitle]) => <Pressable key={title} style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowSub}>{subtitle}</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}<View style={styles.appearance}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>Appearance</Text><Text style={styles.rowSub}>Light or dark theme</Text></View><View style={styles.toggle}><View style={styles.toggleActive}><Text style={styles.toggleActiveText}>Light</Text></View><View style={styles.toggleItem}><Text style={styles.toggleText}>Dark</Text></View></View></View><Pressable style={styles.row}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>Help & Support</Text><Text style={styles.rowSub}>FAQs, yesKaro Assistant and contact support</Text></View><Text style={styles.chevron}>›</Text></Pressable></View><Button label="Sign out" variant="secondary" onPress={() => { logout(); router.replace('/'); }} /></Page>;
}
const styles = StyleSheet.create({
  avatar: { width: 69, height: 69, borderRadius: 35, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.white, fontFamily: fonts.semibold, fontSize: 19 }, verified: { color: colors.success, fontFamily: fonts.medium, fontSize: 9.5 }, rows: { gap: 8 }, row: { height: 48, backgroundColor: colors.surfaceSubtle, borderRadius: 12, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center' }, rowTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: 10.5 }, rowSub: { color: colors.muted, fontFamily: fonts.regular, fontSize: 8.5 }, chevron: { color: colors.tertiary, fontFamily: fonts.regular, fontSize: 17 }, appearance: { height: 48, backgroundColor: colors.surfaceSubtle, borderRadius: 12, paddingLeft: 12, paddingRight: 4, flexDirection: 'row', alignItems: 'center' }, toggle: { width: 166, height: 40, borderWidth: 1, borderColor: colors.border, borderRadius: 13, flexDirection: 'row', padding: 3 }, toggleActive: { flex: 1, borderRadius: 10, backgroundColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, toggleItem: { flex: 1, alignItems: 'center', justifyContent: 'center' }, toggleActiveText: { color: colors.white, fontFamily: fonts.medium, fontSize: 12 }, toggleText: { color: colors.muted, fontFamily: fonts.medium, fontSize: 12 },
});
